[project]
name = "datalake-mcp-server"
version = "0.1.0"
description = "BERDL Datalake MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.121.2",
    "uvicorn==0.38.0",
    "fastapi-mcp==0.4.0",
    "mcp==1.21.2",
    "aiohttp==3.13.2",
    "cacheout==0.16.0",
    "psycopg==3.2.12",
    "sqlparse==0.5.3",
    "ruff==0.14.4",
    "berdl_notebook_utils",
]

[tool.uv.sources]
berdl_notebook_utils = { git = "https://github.com/BERDataLakehouse/spark_notebook.git", subdirectory = "notebook_utils", rev = "main" }

[dependency-groups]
dev = [
    "ipython==9.7.0",
    "pytest==9.0.0",
    "pytest-cov==7.0.0",
]